# Generated by Django 2.2.16 on 2022-01-24 06:30

import reviews.validator_year
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220123_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Укажите год выпуска', validators=[reviews.validator_year.validator], verbose_name='Год выпуска'),
        ),
    ]
